import Layout from "@/components/Layout/Layout";
import "./globals.css";
import { CartProvider } from "@/context/AppContext";

export const metadata = {
  title: "Code Test 2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <>
          <CartProvider>
            <Layout>{children}</Layout>
          </CartProvider>
        </>
      </body>
    </html>
  );
}
