"use client";
import Layout from "@/components/Layout/Layout";
import "./globals.css";
import { CartProvider } from "@/context/AppContext";
import Providers from "./providers";
import ThemeSwitcher from "./ThemeSwitcher";

// export const metadata = {
//   title: "Code Test 2",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <>
          <Providers>
            <CartProvider>
              <Layout>
              <ThemeSwitcher/>
              {children}
              </Layout>
            </CartProvider>
          </Providers>
        </>
      </body>
    </html>
  );
}
